version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    commit-message:
      prefix: deps(ghactions)
    schedule:
      interval: "weekly"
    labels: [dependencies]

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: deps(java)
    labels: [dependencies]
