name: Build and test (on commits and PRs)

on: 
  workflow_dispatch:
    # Allow manual dispatch.

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  tests:
    name: run checks

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk-version: [ '21', '25' ]

    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    with:
      gradle-options:
      os: ${{ matrix.os }}
      jdk-version: ${{ matrix.jdk-version }}
